FROM node:14.16.0-alpine3.12

RUN mkdir -p /client

COPY . ./client
WORKDIR /client

COPY package.json ./

RUN npm install -g serve

RUN npm install

RUN npm run build

EXPOSE 8686

# CMD ["npm", "start"]

CMD ["serve", "-s", "build", "-l", "8686"]