export const LAYOUT_LEFT_SIDEBAR_TOGGLE = 'LAYOUT_LEFT_SIDEBAR_TOGGLE';

export const LAYOUT_LEFT_SIDEBAR_SHOW = 'LAYOUT_LEFT_SIDEBAR_SHOW';

export const LAYOUT_LEFT_SIDEBAR_HIDE = 'LAYOUT_LEFT_SIDEBAR_HIDE';

export const LAYOUT_RIGHT_SIDEBAR_TOGGLE = 'LAYOUT_RIGHT_SIDEBAR_TOGGLE';

export const LAYOUT_RIGHT_SIDEBAR_SHOW = 'LAYOUT_RIGHT_SIDEBAR_SHOW';

export const LAYOUT_RIGHT_SIDEBAR_HIDE = 'LAYOUT_RIGHT_SIDEBAR_HIDE';

export const LAYOUT_WINDOW_RESIZE = 'LAYOUT_WINDOW_RESIZE';

export const LAYOUT_SOUND_TOGGLE = 'LAYOUT_SOUND_TOGGLE';
