export const LAYOUT_LEFT_SIDEBAR_TOGGLE = 'LAYOUT_LEFT_SIDEBAR_TOGGLE';

export const LAYOUT_LEFT_SIDEBAR_SHOW = 'LAYOUT_LEFT_SIDEBAR_SHOW';

export const LAYOUT_LEFT_SIDEBAR_HIDE = 'LAYOUT_LEFT_SIDEBAR_HIDE';

export const LAYOUT_RIGHT_SIDEBAR_TOGGLE = 'LAYOUT_RIGHT_SIDEBAR_TOGGLE';

export const LAYOUT_RIGHT_SIDEBAR_SHOW = 'LAYOUT_RIGHT_SIDEBAR_SHOW';

export const LAYOUT_RIGHT_SIDEBAR_HIDE = 'LAYOUT_RIGHT_SIDEBAR_HIDE';

export const LAYOUT_WINDOW_RESIZE = 'LAYOUT_WINDOW_RESIZE';

export const LAYOUT_SOUND_TOGGLE = 'LAYOUT_SOUND_TOGGLE';

// snackbar
export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_ERROR = 'SNACKBAR_ERROR';
export const SNACKBAR_INFO = 'SNACKBAR_INFO';
export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';
